export const HOBBY_LIMITS = [
  {
    planName: "hobby",
    metricKey: "active_cpu_hours",
    displayName: "Active CPU",
    limitValue: 4,
    unit: "CPU-hrs",
    sourceNote: "Vercel Hobby plan - Active CPU: 4 CPU-hrs/month",
    lastVerifiedAt: new Date("2026-06-09"),
  },
  {
    planName: "hobby",
    metricKey: "provisioned_memory",
    displayName: "Provisioned Memory",
    limitValue: 360,
    unit: "GB-hrs",
    sourceNote: "Vercel Hobby plan - Provisioned Memory: 360 GB-hrs/month",
    lastVerifiedAt: new Date("2026-06-09"),
  },
  {
    planName: "hobby",
    metricKey: "edge_requests",
    displayName: "Edge Requests",
    limitValue: 1000000,
    unit: "requests",
    sourceNote: "Vercel Hobby plan - Edge Requests: 1,000,000/month",
    lastVerifiedAt: new Date("2026-06-09"),
  },
  {
    planName: "hobby",
    metricKey: "function_invocations",
    displayName: "Function Invocations",
    limitValue: 1000000,
    unit: "invocations",
    sourceNote: "Vercel Hobby plan - Function Invocations: 1,000,000/month",
    lastVerifiedAt: new Date("2026-06-09"),
  },
  {
    planName: "hobby",
    metricKey: "fast_data_transfer",
    displayName: "Fast Data Transfer",
    limitValue: 100,
    unit: "GB",
    sourceNote: "Vercel Hobby plan - Bandwidth: 100 GB/month",
    lastVerifiedAt: new Date("2026-06-09"),
  },
  {
    planName: "hobby",
    metricKey: "isr_reads",
    displayName: "ISR Reads",
    limitValue: 1000000,
    unit: "reads",
    sourceNote: "Vercel Hobby plan - ISR Reads: 1,000,000/month",
    lastVerifiedAt: new Date("2026-06-09"),
  },
  {
    planName: "hobby",
    metricKey: "isr_writes",
    displayName: "ISR Writes",
    limitValue: 200000,
    unit: "writes",
    sourceNote: "Vercel Hobby plan - ISR Writes: 200,000/month",
    lastVerifiedAt: new Date("2026-06-09"),
  },
  {
    planName: "hobby",
    metricKey: "build_execution_minutes",
    displayName: "Build Execution",
    limitValue: 6000,
    unit: "minutes",
    sourceNote: "Vercel Hobby plan - Build Execution: 6,000 minutes/month",
    lastVerifiedAt: new Date("2026-06-09"),
  },
  {
    planName: "hobby",
    metricKey: "project_count",
    displayName: "Projects",
    limitValue: 200,
    unit: "projects",
    sourceNote: "Vercel Hobby plan - Projects: 200",
    lastVerifiedAt: new Date("2026-06-09"),
  },
];
